[package]
name = "stm32l4x5"
version = "0.2.0"
authors = ["Eugene Tolmachev <eugene.tolmachev@prolucid.ca>"]

[dependencies]
cortex-m = "0.4.0"
vcell = "0.1.0"
bare-metal = "0.1.1"

[dependencies.cortex-m-rt]
optional = true
version = "0.4.0"

[features]
rt = ["cortex-m-rt"]